version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root

  spring-boot-app:
    image: personalized-data
    ports:
      - "8080:8080"
    depends_on:
      - mysql
